services:
  piston:
    image: ghcr.io/engineer-man/piston
    container_name: vyra-piston
    privileged: true
    ports:
      - "127.0.0.1:2000:2000"
    volumes:
      - piston_data:/piston
    restart: unless-stopped

volumes:
  piston_data:
